# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/markr/Documents/configurable_multiplier/configurable_multiplier.srcs/sources_1/ip/clk_mod/clk_mod.xci
# IP: The module: 'clk_mod' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/markr/Documents/configurable_multiplier/configurable_multiplier.srcs/sources_1/ip/clk_mod/clk_mod_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mod'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/markr/Documents/configurable_multiplier/configurable_multiplier.srcs/sources_1/ip/clk_mod/clk_mod.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mod'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/markr/Documents/configurable_multiplier/configurable_multiplier.srcs/sources_1/ip/clk_mod/clk_mod_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mod'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/markr/Documents/configurable_multiplier/configurable_multiplier.srcs/sources_1/ip/clk_mod/clk_mod.xci
# IP: The module: 'clk_mod' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/markr/Documents/configurable_multiplier/configurable_multiplier.srcs/sources_1/ip/clk_mod/clk_mod_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mod'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/markr/Documents/configurable_multiplier/configurable_multiplier.srcs/sources_1/ip/clk_mod/clk_mod.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mod'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/markr/Documents/configurable_multiplier/configurable_multiplier.srcs/sources_1/ip/clk_mod/clk_mod_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mod'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
